package BankingApp;


/**
* BankingApp/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Banking.idl
* Thursday, May 21, 2026 3:01:18 PM IST
*/

public interface AccountOperations 
{
  double getBalance (String accNo);
  void deposit (String accNo, double amount);
  void withdraw (String accNo, double amount) throws BankingApp.InsufficientBalance;
} // interface AccountOperations
