package BankingApp;


/**
* BankingApp/Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Banking.idl
* Thursday, May 21, 2026 3:01:18 PM IST
*/

public interface Account extends AccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Account
